name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main # Pastikan nama branch Anda 'main' atau 'master'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # TAMBAHAN PENTING: Mengatur Node.js ke versi 20 (Wajib untuk Next.js 16)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Install dan Build
      - name: Install Dependencies and Build
        run: npm ci && npm run build

      # Deploy ke Firebase
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_HERU }}' # Pastikan nama secret ini sesuai dengan yang ada di file lama Anda
          channelId: live
          projectId: portfolio-heru